spring.application.name=restaurant

# cấu hình kết nối sql server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=QL_NHAHANG_CNJAVA;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=1234ngay
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

